# Generated by Django 4.0.4 on 2022-05-17 18:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paczka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('obligatory', models.BooleanField()),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paczka.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('author_surname', models.CharField(max_length=80)),
                ('author_email', models.EmailField(max_length=254)),
                ('path_to_file', models.CharField(max_length=160)),
                ('descripton', models.TextField()),
                ('upload_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paczka.course')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paczka.course'),
        ),
    ]
